CREATE TABLE [dbo].[Yloc]
(
	[Id] INT NOT NULL PRIMARY KEY, 
    [s1] NUMERIC NULL, 
    [s2] NUMERIC NULL, 
    [s3] NUMERIC NULL, 
    [s4] NUMERIC NULL, 
    [s5] NUMERIC NULL, 
    [s6] NUMERIC NULL,
	[s7] NUMERIC NULL,
	[s8] NUMERIC NULL,
	[s9] NUMERIC NULL,
	[s10] NUMERIC NULL,
	[s11] NUMERIC NULL,
	[s12] NUMERIC NULL,
	[s13] NUMERIC NULL,
	[s14] NUMERIC NULL,
	[s15] NUMERIC NULL,
	[s16] NUMERIC NULL,
	[s17] NUMERIC NULL,
	[s18] NUMERIC NULL,
	[s19] NUMERIC NULL,
	[s20] NUMERIC NULL,
	[s21] NUMERIC NULL,
	[s22] NUMERIC NULL,
	[s23] NUMERIC NULL,
	[s24] NUMERIC NULL,
	[s25] NUMERIC NULL,
	[s26] NUMERIC NULL,
	[s27] NUMERIC NULL,
	[s28] NUMERIC NULL,
	[s29] NUMERIC NULL,
	[s30] NUMERIC NULL
)
GO




